name: socket_utils
description: A sample dart application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
homepage: https://b1101-portfolio.web.app

environment:
  sdk: ^3.5.1

dependencies:
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
